---
- name: Chrome add key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Chrome add repo
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    file: /etc/apt/sources.list.d/google-chrome.list
    state: present
    update_cache: yes

- name: Chrome install
  apt:
    pkg: google-chrome-stable
