---
# Following https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04
# for Ubuntu 16.04
- name: Docker ensure HTTPS transport available for APT
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl

- name: Docker add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Docker add repository to apt sources
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    update_cache: yes

- name: Docker install
  apt:
   name: docker-ce
   state: present

- name: Docker add user to docker group
  user:
    name: '{{ user_name }}'
    groups: docker
    append: yes
