---
- name: Install laptop apt packages
  apt: pkg={{ item }} state=latest
  with_items:
      - meld
      - sl
      - atom
      - okular
      - gwenview
      - stacer
      - libreoffice
      - nfs-common
      - rdesktop

- name: Update all packages after install
  apt:
    update_cache: yes

- include: dotfiles.yml
  become: yes
  become_method: sudo
  become_user: "{{ user_name }}"

- include: dropbox.yml

- include: docker.yml

- include: brave.yml

- include: chrome.yml

- include: firefox.yml

- include: sublime.yml

#- name: Acquire Ngrok
#  command: wget ngrok, place in /usr/local/bin or wherever else we put our scripts

- include: virt-manager.yml

- include: spotify.yml

- include: etcher.yml

- include: git-kraken.yml

- include: virtual-box.yml
