---
- name: Install laptop apt packages
  apt: pkg={{ item }} state=latest
  with_items:
      - meld
      - sl
      - atom
      - okular
      - gwenview
      - stacer
      - libreoffice

- name: Update all packages after install
  apt:
    update_cache: yes

- import_tasks: dotfiles.yml
  become: yes
  become_method: sudo
  become_user: "{{ sudo_user }}"

- import_tasks: dropbox.yml

- import_tasks: docker.yml

- import_tasks: brave.yml

- import_tasks: chrome.yml

- import_tasks: firefox.yml

- import_tasks: sublime.yml

#- name: Acquire Ngrok
#  command: wget ngrok, place in /usr/local/bin or wherever else we put our scripts

- import_tasks: virt-manager.yml

- import_tasks: spotify.yml

- import_tasks: etcher.yml
