---
- name: Install laptop apt packages
  apt: pkg={{ item }} state=latest
  with_items:
      - meld
      - sl
      - atom

- name: Update all packages after install
  apt:
    update_cache: yes

- import_tasks: dotfiles.yml
  become: yes
  become_method: sudo
  become_user: "{{ sudo_user }}"
- import_tasks: dropbox.yml

#- import_tasks: docker.yml
