# # 1. Add the Spotify repository signing keys to be able to verify downloaded packages
# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886 0DF731E45CE24F27EEEB1450EFDC8610341D9410
#
# # 2. Add the Spotify repository
# echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
#
# # 3. Update list of available packages
# sudo apt-get update
#
# # 4. Install Spotify
# sudo apt-get install spotify-client


- name: Spotify add apt keys 01-2017
  become: true
  apt_key:
    keyserver: pool.sks-keyservers.net
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886
    state: present

- name: Spotify add repository
  become: true
  apt_repository:
    repo: 'deb http://repository.spotify.com stable non-free'

- name: Spotify install
  become: true
  apt:
    name: spotify-client
    update_cache: yes
    state: latest
