---
# https://www.virtualbox.org/wiki/Linux_Downloads
# https://askubuntu.com/questions/367248/how-to-install-virtualbox-from-command-line/713526#713526

- name: VirtualBox add key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: VirtualBox add repo
  apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }}  contrib
    file: /etc/apt/sources.list
    update_cache: yes

- name: VirtualBox install
  apt:
    pkg: virtualbox-5.2

- name: VirtualBox dkms install
  apt:
    pkg: dkms


