- name: install apt packages
  become: true
  apt: pkg={{ item }} state=latest
  with_items:
      - curl
      - make
      - sl
      - tar
      - vim
      - wget
      - zip
      - curl
      - gcc
      - git
      - less
      - meld

# If we put become:true here, do we not have to within the include?
- include:
    spotify.yml


- name: Update all packages after install
  become: true
  apt:
    update_cache: yes
