- name: install apt packages
  become: true
  apt: pkg={{ item }} state=latest
  with_items:
      - make
      - tar
      - vim
      - wget
      - zip
      - curl
      - gcc
      - git
      - less
      - net-tools
      - apt-transport-https
      - build-essential
      - gparted
      - rar
      - unrar
      - p7zip
      - p7zip-full
      - gdebi
      - ufw
      - nmap
      - ncdu
      - figlet
      - sl
      - elinks
      - nasm
      - cowsay


- name: Update all packages after install
  become: true
  apt:
    update_cache: yes
